### ISSUE TITLE
Clicking on the create new project button results in the application taking sometimes ~20 seconds before it loads.

### ISSUE THREAD

**Issue by overZellis133** [C2DH/tim#111]
<img width="1439" alt="React_App" src="https://user-images.githubusercontent.com/14208691/100524995-148e0900-318b-11eb-987d-773fe9d444c3.png">

**Comment by maboa** [comment]
@overZellis133 is there any way you can describe the conditions to make this bug repeatable. I assume it goes away when you do `localStorage.clear()` in the console ?

**Comment by maboa** [comment]
I wonder if using Chrome devtools would help us debug @Laurian ? https://developers.google.com/web/tools/chrome-devtools/storage/localstorage

**Comment by Laurian** [comment]
afaik this was fixed
